{% set name = "nappy" %}
{% set version = "2.0.0" %}
{% set sha256 = "1d7c983b108ccb84018867894a0a4e56367440fb9d1b5c65569cf3409139f0f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win or py3k]
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - numpy
    - cdat-lite
    - python

test:
  imports:
    - nappy
    - nappy.utils.compare_na
    - nappy.utils.common_utils
    - nappy.utils.text_parser

about:
  home: https://github.com/cedadev/nappy
  license: BSD 3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: A NASA AMes I/O package

extra:
  recipe-maintainers:
    - ReimarBauer
